[package]
name = "sam_onnx_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ort = "1.15.2"
image = "0.24.7"
ndarray = "0.15.6"
rocket = "0.5.0-rc.3"
serde_json = "1.0.36"
